In [37]:
import pandas as pd
import numpy as np
import mlflow
import dagshub
import optuna
from pathlib import Path
from sklearn.model_selection import train_test_split,cross_val_score,cross_validate
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler,OrdinalEncoder,PowerTransformer
from sklearn.metrics import mean_absolute_error,r2_score
from sklearn.ensemble import RandomForestRegressor , GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

In [5]:
root_dir = Path.cwd().parent
data_dir = root_dir / 'data' / 'interim' / 'urbaneats-cleaned-dataset.csv'

In [6]:
df = pd.read_csv(data_dir)

In [7]:
df.head()

           rider_id   age  ratings  ...  order_time_of_day   distance  distance_type
0   INDORES13DEL02   37.0      4.9  ...            morning   3.025149          short
1   BANGRES18DEL02   34.0      4.5  ...            evening  20.183530      very_long
2   BANGRES19DEL01   23.0      4.4  ...            morning   1.552758          short
3  COIMBRES13DEL02   38.0      4.7  ...            evening   7.790401         medium
4   CHENRES12DEL01   32.0      4.6  ...          afternoon   6.210138         medium

[5 rows x 27 columns]

In [8]:
df.shape

(45502, 27)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:

# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city",
                    "order_day_of_week",
                    "order_month"]

df.drop(columns=columns_to_drop, inplace=True)

df

        age  ratings     weather  ... order_time_of_day   distance distance_type
0      37.0      4.9       sunny  ...           morning   3.025149         short
1      34.0      4.5      stormy  ...           evening  20.183530     very_long
2      23.0      4.4  sandstorms  ...           morning   1.552758         short
3      38.0      4.7       sunny  ...           evening   7.790401        medium
4      32.0      4.6      cloudy  ...         afternoon   6.210138        medium
...     ...      ...         ...  ...               ...        ...           ...
45497  30.0      4.8       windy  ...           morning   1.489846         short
45498  21.0      4.6       windy  ...           evening        NaN           NaN
45499  30.0      4.9      cloudy  ...             night   4.657195         short
45500  20.0      4.7      cloudy  ...         afternoon   6.232393        medium
45501  23.0      4.9         fog  ...         afternoon  12.074396          long

[45502 rows x 16 columns]

In [11]:
# check for missing values

df.isna().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
type_of_order             0
type_of_vehicle           0
multiple_deliveries     993
festival                228
city_type              1198
time_taken                0
is_weekend                0
pickup_time_minutes    1640
order_time_of_day      2070
distance               3630
distance_type          3630
dtype: int64

In [12]:
dagshub.init(repo_owner='AvanindraBose', repo_name='Urban-Eats-Food-Delivery-Time-Prediction', mlflow=True)

Accessing as AvanindraBose

Initialized MLflow to track repo "AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction"

Repository AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction initialized!

In [13]:
mlflow.set_tracking_uri('https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow')

# Droping Missing Values and then Slecting the 2 Best Model.

In [14]:
temp_df = df.copy().dropna()

In [15]:
temp_df.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [16]:
temp_df.shape

(37695, 16)

In [17]:
X = temp_df.drop(columns= ['time_taken'])
y = temp_df['time_taken']

In [18]:
X.sample(10)

        age  ratings     weather  ... order_time_of_day   distance distance_type
25273  36.0      4.5         fog  ...             night  10.587816          long
18122  29.0      4.3         fog  ...           evening  19.761110     very_long
29845  31.0      4.8       sunny  ...             night  14.021757          long
24140  27.0      4.7       sunny  ...           morning   3.018827         short
28849  31.0      4.5      cloudy  ...           evening  20.179033     very_long
14187  33.0      4.2       windy  ...             night  12.236791          long
35953  37.0      4.6       windy  ...           evening  13.973183          long
43133  36.0      4.7         fog  ...             night   7.790439        medium
21182  23.0      4.9         fog  ...         afternoon   5.968814        medium
12217  39.0      4.5  sandstorms  ...         afternoon  16.722119     very_long

[10 rows x 15 columns]

In [19]:
y.sample(10)

19174    23
15566    34
19477    42
10214    14
18240    14
8928     30
30673    27
44053    26
10169    22
17687    25
Name: time_taken, dtype: int64

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
print("The size of train data is",X_train.shape)
print("The shape of test data is",X_test.shape)

The size of train data is (30156, 15)
The shape of test data is (7539, 15)

In [22]:
temp_df.dtypes

age                    float64
ratings                float64
weather                 object
traffic                 object
vehicle_condition        int64
type_of_order           object
type_of_vehicle         object
multiple_deliveries    float64
festival                object
city_type               object
time_taken               int64
is_weekend               int64
pickup_time_minutes    float64
order_time_of_day       object
distance               float64
distance_type           object
dtype: object

In [23]:
num_cols = X_train.select_dtypes(include=np.number).columns.to_list()

In [24]:
num_cols.remove('vehicle_condition')
num_cols.remove('multiple_deliveries')

In [25]:
num_cols

['age', 'ratings', 'is_weekend', 'pickup_time_minutes', 'distance']

In [26]:
X_train.select_dtypes(include=object).columns.to_list()

['weather',
 'traffic',
 'type_of_order',
 'type_of_vehicle',
 'festival',
 'city_type',
 'order_time_of_day',
 'distance_type']

In [27]:
ordinal_cat_cols = ['traffic','distance_type']

nominal_cat_cols = [
    'weather',
    'type_of_order',
    'type_of_vehicle',
    'festival',
    'city_type',
    'order_time_of_day'
]

In [28]:
len(num_cols + nominal_cat_cols + ordinal_cat_cols)

13

In [29]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [31]:
preprocessor = ColumnTransformer(
    transformers=[
        ('numerical columns',MinMaxScaler(),num_cols),
        ('nominal categorical columns',OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False),nominal_cat_cols),
        ('ordinal categorical columns', OrdinalEncoder(categories=[traffic_order,distance_type_order]),ordinal_cat_cols)
    ],remainder='passthrough',n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False
)

In [42]:
pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", RandomForestRegressor(random_state=42))
    ])

model_pipe_tt = TransformedTargetRegressor(
        regressor=pipeline,
        transformer=PowerTransformer()
    )

In [38]:
scores = cross_validate(
            model_pipe_tt,
            X_train,
            y_train,
            cv = 5,
            scoring = {
                "mae":"neg_mean_absolute_error",
                "r2":"r2"
            },
            n_jobs = -1,
            return_train_score = True
        )

In [39]:
scores

{'fit_time': array([20.5118382 , 20.51391029, 20.39933133, 20.6051693 , 20.60942173]),
 'score_time': array([0.33383083, 0.32973909, 0.37485766, 0.31027222, 0.30884981]),
 'test_mae': array([-3.13546104, -3.12235661, -3.12444186, -3.11345066, -3.12149127]),
 'train_mae': array([-1.15979466, -1.16200418, -1.16248186, -1.16374641, -1.15388512]),
 'test_r2': array([0.82461643, 0.8266513 , 0.82691264, 0.82564512, 0.82780124]),
 'train_r2': array([0.97533032, 0.97527773, 0.97529923, 0.97521568, 0.97559166])}

In [44]:
model_pipe_tt.regressor.named_steps['model'].__class__.__name__

'RandomForestRegressor'

In [40]:
def build_model(trial):
    model_name = trial.suggest_categorical("model", ["RF", "GB", "XGB", "KNN"])

    if model_name == "RF":
        model = RandomForestRegressor(
            n_estimators=trial.suggest_int("rf_n_estimators", 100, 500),
            max_depth=trial.suggest_int("rf_max_depth", 3, 30),
            min_samples_leaf=trial.suggest_int("rf_min_samples_leaf", 1, 10),
            random_state=42,
            n_jobs=-1
        )

    elif model_name == "GB":
        model = GradientBoostingRegressor(
            n_estimators=trial.suggest_int("gb_n_estimators", 100, 500),
            learning_rate=trial.suggest_float("gb_learning_rate", 0.01, 0.2, log=True),
            max_depth=trial.suggest_int("gb_max_depth", 2, 8),
            random_state=42
        )

    elif model_name == "XGB":
        model = XGBRegressor(
            n_estimators=trial.suggest_int("xgb_n_estimators", 100, 600),
            learning_rate=trial.suggest_float("xgb_learning_rate", 0.01, 0.2, log=True),
            max_depth=trial.suggest_int("xgb_max_depth", 2, 10),
            subsample=trial.suggest_float("xgb_subsample", 0.6, 1.0),
            colsample_bytree=trial.suggest_float("xgb_colsample_bytree", 0.6, 1.0),
            random_state=42,
            n_jobs=-1
        )

    else:
        model = KNeighborsRegressor(
            n_neighbors=trial.suggest_int("knn_n_neighbors", 3, 40),
            weights=trial.suggest_categorical("knn_weights", ["uniform", "distance"])
        )

    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    model_pipe = TransformedTargetRegressor(
        regressor=pipeline,
        transformer=PowerTransformer()
    )

    return model_pipe

In [45]:
def objective(trial):
    with mlflow.start_run(run_name=f"trial_{trial.number}", nested=True):

        model_pipe = build_model(trial)

        scores = cross_validate(
            model_pipe,
            X_train,
            y_train,
            cv = 5,
            scoring = {
                "mae":"neg_mean_absolute_error",
                "r2":"r2"
            },
            n_jobs = -1,
            return_train_score = True
        )

        train_mae = -scores["train_mae"].mean()
        val_mae = -scores["test_mae"].mean()
        val_mae_std = scores["test_mae"].std()
        train_r2 = scores["train_r2"].mean()
        val_r2 = scores["test_r2"].mean()

        mlflow.log_param("model_type",model_pipe.regressor.named_steps['model'].__class__.__name__)
        mlflow.log_param("trial_number", trial.number)
        mlflow.log_params(trial.params)

        mlflow.log_metric("train_mae_mean", train_mae)
        mlflow.log_metric("val_mae_mean", val_mae)
        mlflow.log_metric("val_mae_std", val_mae_std)
        mlflow.log_metric("train_r2_mean", train_r2)
        mlflow.log_metric("val_r2_mean", val_r2)

        for i, score in enumerate(scores["test_mae"]):
            mlflow.log_metric(f"fold_{i}_val_mae", -score)

        for i, score in enumerate(scores["test_r2"]):
            mlflow.log_metric(f"fold_{i}_val_r2", score)

        trial.set_user_attr("val_mae", val_mae)
        trial.set_user_attr("val_r2", val_r2)

        return val_mae

In [46]:
mlflow.set_experiment('Exp2 : Selecting 2 Best Models')
study = optuna.create_study(direction="minimize",study_name="model_selection")


with mlflow.start_run(run_name= 'Best Model') as parent_run:
    mlflow.log_param("n_trials",50)
    mlflow.log_param("cv_folds",5)
    mlflow.log_param("objective_metric","val_mae")

    study.optimize(objective,n_trials=50)

    best_trial = study.best_trial

    mlflow.log_param("best_trial_number", best_trial.number)
    mlflow.log_param("best_model", best_trial.params["model"])

    for key,value in best_trial.params.items():
        mlflow.log_param(f"best_{key}",value)
    
    mlflow.log_metric("best_cv_mae",best_trial.value)

    trials_df = study.trials_dataframe()
    trials_df.to_csv("optuna_trials.csv", index=False)
    mlflow.log_artifact("optuna_trials.csv")

    best_model_pipe = build_model(best_trial)
    best_model_pipe.fit(X_train,y_train)

    y_pred_train = best_model_pipe.predict(X_train)
    y_pred_test = best_model_pipe.predict(X_test)
    
    train_mae = mean_absolute_error(y_train, y_pred_train)
    test_mae = mean_absolute_error(y_test, y_pred_test)

    train_r2 = r2_score(y_train, y_pred_train)
    test_r2 = r2_score(y_test, y_pred_test)

    mlflow.log_params(best_trial.params)

    mlflow.log_metric("train_mae", train_mae)
    mlflow.log_metric("test_mae", test_mae)
    mlflow.log_metric("train_r2", train_r2)
    mlflow.log_metric("test_r2", test_r2)

    mlflow.sklearn.log_model(best_model_pipe, "model")

2026/06/03 06:49:57 INFO mlflow.tracking.fluent: Experiment with name 'Exp2 : Selecting 2 Best Models' does not exist. Creating a new experiment.
[I 2026-06-03 06:49:58,412] A new study created in memory with name: model_selection

🏃 View run trial_0 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/64fb514aac4d4bac9a151389d1a0d735
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:50:25,485] Trial 0 finished with value: 3.0933066286260607 and parameters: {'model': 'RF', 'rf_n_estimators': 206, 'rf_max_depth': 30, 'rf_min_samples_leaf': 5}. Best is trial 0 with value: 3.0933066286260607.

🏃 View run trial_1 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/76f016b5d42c4d05b2817899ac95aa2c
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:51:03,687] Trial 1 finished with value: 4.449116185038251 and parameters: {'model': 'KNN', 'knn_n_neighbors': 39, 'knn_weights': 'distance'}. Best is trial 0 with value: 3.0933066286260607.

🏃 View run trial_2 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/227dc79873e04f61b7d7a0351cd2f5a8
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:52:15,217] Trial 2 finished with value: 3.1295397306771937 and parameters: {'model': 'GB', 'gb_n_estimators': 373, 'gb_learning_rate': 0.08228612682009882, 'gb_max_depth': 8}. Best is trial 0 with value: 3.0933066286260607.

🏃 View run trial_3 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/19b1cdeb69a643c7a3341a3236965a48
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:52:48,742] Trial 3 finished with value: 3.6248758073485363 and parameters: {'model': 'GB', 'gb_n_estimators': 423, 'gb_learning_rate': 0.10190671580017227, 'gb_max_depth': 2}. Best is trial 0 with value: 3.0933066286260607.

🏃 View run trial_4 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/3058a47721c64cf4a0428a05331581b0
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:53:36,787] Trial 4 finished with value: 4.350362473099761 and parameters: {'model': 'KNN', 'knn_n_neighbors': 8, 'knn_weights': 'distance'}. Best is trial 0 with value: 3.0933066286260607.

🏃 View run trial_5 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/32118e3a26104263b8d462dcc8319306
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:54:21,472] Trial 5 finished with value: 3.08891729529703 and parameters: {'model': 'RF', 'rf_n_estimators': 282, 'rf_max_depth': 25, 'rf_min_samples_leaf': 9}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_6 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/1132be742a564a69b25082194d42a25c
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:54:52,700] Trial 6 finished with value: 4.701707636694281 and parameters: {'model': 'RF', 'rf_n_estimators': 252, 'rf_max_depth': 4, 'rf_min_samples_leaf': 9}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_7 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/70da8df4b0e548fc938daf0c22480020
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:55:47,949] Trial 7 finished with value: 3.824287234222607 and parameters: {'model': 'GB', 'gb_n_estimators': 288, 'gb_learning_rate': 0.01832227912210805, 'gb_max_depth': 3}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_8 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/9b4dfae9767943da805653392736566e
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:56:40,674] Trial 8 finished with value: 3.108052158355713 and parameters: {'model': 'XGB', 'xgb_n_estimators': 552, 'xgb_learning_rate': 0.0162585599697831, 'xgb_max_depth': 9, 'xgb_subsample': 0.8423601278320244, 'xgb_colsample_bytree': 0.6281879073598188}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_9 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/1002ac30480741179fb1e9b40e8c255b
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:57:19,256] Trial 9 finished with value: 3.594484662848848 and parameters: {'model': 'GB', 'gb_n_estimators': 414, 'gb_learning_rate': 0.024476398540546812, 'gb_max_depth': 3}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_10 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/dd7907d2a59747b8863b8af7c8bf7d67
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:58:40,085] Trial 10 finished with value: 3.114146938342605 and parameters: {'model': 'RF', 'rf_n_estimators': 496, 'rf_max_depth': 30, 'rf_min_samples_leaf': 1}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_11 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/aabd5a6c86394e3280db907e1665935b
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 06:59:16,978] Trial 11 finished with value: 3.089750053922236 and parameters: {'model': 'RF', 'rf_n_estimators': 218, 'rf_max_depth': 29, 'rf_min_samples_leaf': 8}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_12 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/9b0c5fe0830f4aefac074bfbde8b4b70
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:00:04,983] Trial 12 finished with value: 3.0890849357830144 and parameters: {'model': 'RF', 'rf_n_estimators': 299, 'rf_max_depth': 22, 'rf_min_samples_leaf': 9}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_13 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/2624a4a9b80044698419da7791c48ae0
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:00:40,992] Trial 13 finished with value: 3.0912643723773656 and parameters: {'model': 'RF', 'rf_n_estimators': 337, 'rf_max_depth': 19, 'rf_min_samples_leaf': 10}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_14 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/52657619040847a0a386e31c935b58e8
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:01:21,646] Trial 14 finished with value: 3.715283679962158 and parameters: {'model': 'XGB', 'xgb_n_estimators': 119, 'xgb_learning_rate': 0.19580917664328576, 'xgb_max_depth': 2, 'xgb_subsample': 0.6206293315377197, 'xgb_colsample_bytree': 0.9955946101840208}. Best is trial 5 with value: 3.08891729529703.

🏃 View run trial_15 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/f6d51c7432ba4f909ff86301a2bbf7aa
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:02:05,011] Trial 15 finished with value: 3.0881262823817286 and parameters: {'model': 'RF', 'rf_n_estimators': 355, 'rf_max_depth': 20, 'rf_min_samples_leaf': 7}. Best is trial 15 with value: 3.0881262823817286.

🏃 View run trial_16 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/6bb95c72551749ffae1c7c4cbe6ca9b4
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:03:01,053] Trial 16 finished with value: 3.0888766153560234 and parameters: {'model': 'RF', 'rf_n_estimators': 396, 'rf_max_depth': 19, 'rf_min_samples_leaf': 6}. Best is trial 15 with value: 3.0881262823817286.

🏃 View run trial_17 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/73e9b7b1e6944793a82c6d037e03e548
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:03:49,227] Trial 17 finished with value: 3.082738338997442 and parameters: {'model': 'RF', 'rf_n_estimators': 415, 'rf_max_depth': 14, 'rf_min_samples_leaf': 6}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_18 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/9ac7ae27550246cb93e307e90c84eca4
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:04:27,917] Trial 18 finished with value: 4.503158154280788 and parameters: {'model': 'KNN', 'knn_n_neighbors': 4, 'knn_weights': 'uniform'}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_19 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/84a09ab3db1e4c6592f9957b44a00ccb
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:05:06,497] Trial 19 finished with value: 3.1019742488861084 and parameters: {'model': 'XGB', 'xgb_n_estimators': 587, 'xgb_learning_rate': 0.012210452110451254, 'xgb_max_depth': 10, 'xgb_subsample': 0.9916586435766803, 'xgb_colsample_bytree': 0.664113026915784}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_20 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/5e52b9db1d3641a4ad947a34d1adff2c
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:05:55,237] Trial 20 finished with value: 3.106135044149002 and parameters: {'model': 'RF', 'rf_n_estimators': 420, 'rf_max_depth': 12, 'rf_min_samples_leaf': 5}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_21 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/b9c87550886649c289bd683660ee8528
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:06:42,887] Trial 21 finished with value: 3.0874927826438645 and parameters: {'model': 'RF', 'rf_n_estimators': 397, 'rf_max_depth': 16, 'rf_min_samples_leaf': 6}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_22 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/e7daf8fb20444f42881c7693c9eb882c
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:07:27,495] Trial 22 finished with value: 3.0832498585754506 and parameters: {'model': 'RF', 'rf_n_estimators': 395, 'rf_max_depth': 14, 'rf_min_samples_leaf': 6}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_23 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/1f8f1899b0314260886c4a62c9a5580a
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:08:06,877] Trial 23 finished with value: 3.0850656973366624 and parameters: {'model': 'RF', 'rf_n_estimators': 445, 'rf_max_depth': 13, 'rf_min_samples_leaf': 4}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_24 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/724e4c417c52451d967168c2cb33b89f
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:08:50,057] Trial 24 finished with value: 3.1769320425062717 and parameters: {'model': 'RF', 'rf_n_estimators': 466, 'rf_max_depth': 11, 'rf_min_samples_leaf': 3}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_25 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/0b2bfbea63494352bfcbf1cac1ee8a34
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:09:39,659] Trial 25 finished with value: 3.1746824670001654 and parameters: {'model': 'RF', 'rf_n_estimators': 451, 'rf_max_depth': 11, 'rf_min_samples_leaf': 4}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_26 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/3370bee203c24a519b7a909dc21e30f4
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:10:24,736] Trial 26 finished with value: 3.084985027939775 and parameters: {'model': 'RF', 'rf_n_estimators': 364, 'rf_max_depth': 14, 'rf_min_samples_leaf': 3}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_27 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/f43b0bd495a742e8a8fbaaa6a9952fd0
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:11:15,769] Trial 27 finished with value: 4.501375808482499 and parameters: {'model': 'KNN', 'knn_n_neighbors': 32, 'knn_weights': 'uniform'}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_28 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/bbfa9292d4aa47459b4b4edb30f7e0f0
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:11:46,623] Trial 28 finished with value: 3.719918060302734 and parameters: {'model': 'XGB', 'xgb_n_estimators': 225, 'xgb_learning_rate': 0.09810106608572353, 'xgb_max_depth': 2, 'xgb_subsample': 0.6371330266918964, 'xgb_colsample_bytree': 0.8994503874609233}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_29 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/78e36e9d8bed46f49e2f3a7d54f242a3
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:12:22,639] Trial 29 finished with value: 3.7482740332001803 and parameters: {'model': 'RF', 'rf_n_estimators': 357, 'rf_max_depth': 7, 'rf_min_samples_leaf': 1}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_30 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/d628bba96188496b80863bc5484da202
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:13:11,018] Trial 30 finished with value: 3.0897996883038683 and parameters: {'model': 'RF', 'rf_n_estimators': 384, 'rf_max_depth': 15, 'rf_min_samples_leaf': 3}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_31 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/1e0718c23d114ecab5cf44e2725e7612
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:13:59,373] Trial 31 finished with value: 3.084517142451998 and parameters: {'model': 'RF', 'rf_n_estimators': 446, 'rf_max_depth': 14, 'rf_min_samples_leaf': 3}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_32 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/df67126260a04404833c6c5a58801d84
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:14:33,327] Trial 32 finished with value: 3.0971440733340545 and parameters: {'model': 'RF', 'rf_n_estimators': 325, 'rf_max_depth': 16, 'rf_min_samples_leaf': 2}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_33 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/fcf489ce44c447aa98fb3bbaf1f362bf
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:15:08,389] Trial 33 finished with value: 3.568357185621662 and parameters: {'model': 'RF', 'rf_n_estimators': 103, 'rf_max_depth': 8, 'rf_min_samples_leaf': 3}. Best is trial 17 with value: 3.082738338997442.

🏃 View run trial_34 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/2fe01b3a5b3c4333a88350d97af051cd
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:16:00,436] Trial 34 finished with value: 3.082680546279501 and parameters: {'model': 'RF', 'rf_n_estimators': 425, 'rf_max_depth': 14, 'rf_min_samples_leaf': 6}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_35 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/95ccdae1339246239754dbf6ecf1f1e8
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:16:44,945] Trial 35 finished with value: 3.165195868328754 and parameters: {'model': 'GB', 'gb_n_estimators': 133, 'gb_learning_rate': 0.1904222742311561, 'gb_max_depth': 8}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_36 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/422ae0a5a310469eb9d0f114bb1b7ca6
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:17:24,261] Trial 36 finished with value: 4.351153402839907 and parameters: {'model': 'KNN', 'knn_n_neighbors': 21, 'knn_weights': 'distance'}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_37 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/2231486f672440e7a9aa71f02f1bddb0
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:18:13,457] Trial 37 finished with value: 3.458222057631514 and parameters: {'model': 'RF', 'rf_n_estimators': 427, 'rf_max_depth': 9, 'rf_min_samples_leaf': 7}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_38 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/ce9ac04d00dd499ca8a407b195972ac1
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:19:10,899] Trial 38 finished with value: 3.0877818969346107 and parameters: {'model': 'RF', 'rf_n_estimators': 488, 'rf_max_depth': 17, 'rf_min_samples_leaf': 6}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_39 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/d71e21a1aac64040b00c0af06d4bc00f
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:19:40,101] Trial 39 finished with value: 4.113328488718523 and parameters: {'model': 'GB', 'gb_n_estimators': 153, 'gb_learning_rate': 0.010323513062211994, 'gb_max_depth': 5}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_40 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/7f3fb07244b242979e6ada3cf7743f80
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:20:32,825] Trial 40 finished with value: 4.422786987316675 and parameters: {'model': 'KNN', 'knn_n_neighbors': 20, 'knn_weights': 'uniform'}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_41 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/78f56544d303484a8594d1ec742fbbca
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:21:09,034] Trial 41 finished with value: 3.083062845003169 and parameters: {'model': 'RF', 'rf_n_estimators': 384, 'rf_max_depth': 14, 'rf_min_samples_leaf': 5}. Best is trial 34 with value: 3.082680546279501.

🏃 View run trial_42 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/f07ea7c1183d48a8b9c531fb2e716de1
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:21:54,699] Trial 42 finished with value: 3.082608422650648 and parameters: {'model': 'RF', 'rf_n_estimators': 418, 'rf_max_depth': 14, 'rf_min_samples_leaf': 5}. Best is trial 42 with value: 3.082608422650648.

🏃 View run trial_43 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/5dc23dba1c3441f2847cab613a09ba1e
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:22:34,516] Trial 43 finished with value: 3.1725825347569843 and parameters: {'model': 'RF', 'rf_n_estimators': 413, 'rf_max_depth': 11, 'rf_min_samples_leaf': 5}. Best is trial 42 with value: 3.082608422650648.

🏃 View run trial_44 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/f9723b9e8cb9491d89a726b3a5e671a2
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:23:20,892] Trial 44 finished with value: 3.0876670240422923 and parameters: {'model': 'RF', 'rf_n_estimators': 374, 'rf_max_depth': 17, 'rf_min_samples_leaf': 7}. Best is trial 42 with value: 3.082608422650648.

🏃 View run trial_45 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/76a5f7f1f17148e8a16006e106364bd7
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:24:02,707] Trial 45 finished with value: 3.0852334998858493 and parameters: {'model': 'RF', 'rf_n_estimators': 411, 'rf_max_depth': 13, 'rf_min_samples_leaf': 6}. Best is trial 42 with value: 3.082608422650648.

🏃 View run trial_46 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/ff3b5ae5777343c2a8c09386ae45db5d
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:25:06,051] Trial 46 finished with value: 3.110757095058572 and parameters: {'model': 'GB', 'gb_n_estimators': 499, 'gb_learning_rate': 0.046706059113080144, 'gb_max_depth': 6}. Best is trial 42 with value: 3.082608422650648.

🏃 View run trial_47 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/702eba1b9bee4a5680a7f821683664b9
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:25:47,696] Trial 47 finished with value: 3.1221107006073 and parameters: {'model': 'XGB', 'xgb_n_estimators': 368, 'xgb_learning_rate': 0.03955486119631612, 'xgb_max_depth': 6, 'xgb_subsample': 0.7947799712582604, 'xgb_colsample_bytree': 0.8109667662850133}. Best is trial 42 with value: 3.082608422650648.

🏃 View run trial_48 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/9e8e1cec89cf4f5dbcad0411e7cb7e05
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:26:25,913] Trial 48 finished with value: 3.323288433925549 and parameters: {'model': 'RF', 'rf_n_estimators': 427, 'rf_max_depth': 10, 'rf_min_samples_leaf': 5}. Best is trial 42 with value: 3.082608422650648.

🏃 View run trial_49 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/359b601d919b482f9d2a7582a8e93aeb
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

[I 2026-06-03 07:27:18,246] Trial 49 finished with value: 3.0880192545134006 and parameters: {'model': 'RF', 'rf_n_estimators': 474, 'rf_max_depth': 15, 'rf_min_samples_leaf': 4}. Best is trial 42 with value: 3.082608422650648.
c:\Users\avanindra Bose\Urban Eats Delivery Time Prediction\UrbanEats-Delivery-Time-Prediction\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:978: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
2026/06/03 07:27:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/03 07:27:52 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/06/03 07:28:08 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run Best Model at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2/runs/1ad5a330bb7e42099f3b03f3909ab3ad
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/2

In [50]:
exp_data = study.trials_dataframe()

In [55]:
exp_data['params_model'].value_counts()

params_model
RF     32
GB      7
KNN     6
XGB     5
Name: count, dtype: int64

In [63]:
exp_data.groupby(exp_data['params_model'])['value'].agg('mean').sort_values(ascending=True)

params_model
RF     3.202053
XGB    3.353468
GB     3.508924
KNN    4.429659
Name: value, dtype: float64

In [64]:
optuna.visualization.plot_optimization_history(study)

In [65]:
# partial coord plot

optuna.visualization.plot_parallel_coordinate(study,params=["model"])

# From this Experimentation I can conclude that I will be using Random Forest and XgBoost as my underlying models in Stacking Ensemble Technique.