In [48]:
import pandas as pd
import numpy as np
import mlflow
import dagshub
import optuna
import json
from pathlib import Path
from sklearn.model_selection import train_test_split,cross_validate
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler,OrdinalEncoder,PowerTransformer
from sklearn.metrics import mean_absolute_error,r2_score
from xgboost import XGBRegressor
from datetime import datetime,timezone

In [2]:
root_dir = Path.cwd().parent
data_dir = root_dir / 'data' / 'interim' / 'urbaneats-cleaned-dataset.csv'

In [3]:
df = pd.read_csv(data_dir)

In [4]:
df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city,order_day,order_month,order_day_of_week,is_weekend,order_time_hour,pickup_time_minutes,order_time_of_day,distance,distance_type
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,INDO,19,3,Saturday,1,11.0,15.0,morning,3.025149,short
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,BANG,25,3,Friday,0,19.0,5.0,evening,20.183530,very_long
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,BANG,19,3,Saturday,1,8.0,15.0,morning,1.552758,short
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,COIMB,5,4,Tuesday,0,18.0,10.0,evening,7.790401,medium
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,CHEN,26,3,Saturday,1,13.0,15.0,afternoon,6.210138,medium

In [5]:
df.shape

(45502, 27)

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city",
                    "order_day_of_week",
                    "order_month"]

df.drop(columns=columns_to_drop, inplace=True)

In [8]:
# check for missing values

df.isna().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
type_of_order             0
type_of_vehicle           0
multiple_deliveries     993
festival                228
city_type              1198
time_taken                0
is_weekend                0
pickup_time_minutes    1640
order_time_of_day      2070
distance               3630
distance_type          3630
dtype: int64

In [9]:
dagshub.init(repo_owner='AvanindraBose', repo_name='Urban-Eats-Food-Delivery-Time-Prediction', mlflow=True)

Accessing as AvanindraBose

Initialized MLflow to track repo "AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction"

Repository AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction initialized!

In [10]:
mlflow.set_tracking_uri('https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow')

# Droping Missing Values and then Selecting the Best HyperParameters for XGB Regressor.

In [11]:
temp_df = df.copy().dropna()

In [12]:
temp_df.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [13]:
temp_df.shape

(37695, 16)

In [14]:
X = temp_df.drop(columns= ['time_taken'])
y = temp_df['time_taken']

In [15]:
X.sample(10)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
11746,27.0,4.6,sunny,low,1,meal,motorcycle,1.0,no,metropolitian,0,10.0,night,20.179004,very_long
13201,26.0,4.8,stormy,low,1,snack,scooter,0.0,no,metropolitian,0,10.0,morning,3.104556,short
40971,27.0,5.0,cloudy,medium,1,snack,scooter,1.0,no,metropolitian,0,10.0,afternoon,13.680927,long
23898,38.0,4.3,stormy,jam,2,drinks,motorcycle,2.0,yes,metropolitian,0,10.0,evening,17.078934,very_long
9921,25.0,5.0,sunny,low,2,meal,electric_scooter,0.0,no,urban,0,15.0,night,12.420599,long
27448,27.0,4.7,windy,medium,1,buffet,motorcycle,1.0,no,urban,0,10.0,evening,4.476869,short
9797,39.0,4.8,stormy,low,1,drinks,motorcycle,1.0,no,metropolitian,0,15.0,morning,2.937443,short
16926,26.0,4.6,sandstorms,jam,2,snack,scooter,1.0,no,metropolitian,1,5.0,evening,7.790337,medium
21283,34.0,4.7,sunny,medium,0,drinks,motorcycle,1.0,no,urban,1,15.0,afternoon,4.657655,short
19470,22.0,4.6,sunny,low,0,buffet,motorcycle,1.0,no,metropolitian,1,5.0,night,19.975696,very_long

In [16]:
y.sample(10)

42604    40
22842    29
42602    29
6915     12
31629    45
5688     22
19308    30
36842    21
23587    43
36371    31
Name: time_taken, dtype: int64

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
print("The size of train data is",X_train.shape)
print("The shape of test data is",X_test.shape)

The size of train data is (30156, 15)
The shape of test data is (7539, 15)

In [19]:
num_cols = X_train.select_dtypes(include=np.number).columns.to_list()

In [20]:
num_cols.remove('vehicle_condition')
num_cols.remove('multiple_deliveries')

In [21]:
X_train.select_dtypes(include=object).columns.to_list()

['weather',
 'traffic',
 'type_of_order',
 'type_of_vehicle',
 'festival',
 'city_type',
 'order_time_of_day',
 'distance_type']

In [22]:
ordinal_cat_cols = ['traffic','distance_type']

nominal_cat_cols = [
    'weather',
    'type_of_order',
    'type_of_vehicle',
    'festival',
    'city_type',
    'order_time_of_day'
]

In [23]:
len(num_cols + nominal_cat_cols + ordinal_cat_cols)

13

In [24]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

__Testing the Pipeline.__

In [25]:
preprocessor = ColumnTransformer(
    transformers=[
        ('numerical columns',MinMaxScaler(),num_cols),
        ('nominal categorical columns',OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False),nominal_cat_cols),
        ('ordinal categorical columns', OrdinalEncoder(categories=[traffic_order,distance_type_order]),ordinal_cat_cols)
    ],remainder='passthrough',n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False
)

In [27]:
pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", XGBRegressor(random_state=42, n_jobs=-1))
    ])

model_pipe_tt = TransformedTargetRegressor(
        regressor=pipeline,
        transformer=PowerTransformer()
    )

In [28]:
scores = cross_validate(
            model_pipe_tt,
            X_train,
            y_train,
            cv = 5,
            scoring = {
                "mae":"neg_mean_absolute_error",
                "r2":"r2"
            },
            n_jobs = -1,
            return_train_score = True
        )

In [29]:
scores

{'fit_time': array([0.56143928, 0.53990722, 0.54390574, 0.5369072 , 0.54941487]),
 'score_time': array([0.0489037 , 0.05159807, 0.04911041, 0.05259943, 0.04760385]),
 'test_mae': array([-3.20097303, -3.1386447 , -3.13769221, -3.12094164, -3.12675405]),
 'train_mae': array([-2.56598568, -2.55687475, -2.5639298 , -2.54815674, -2.54575753]),
 'test_r2': array([0.81691056, 0.8251425 , 0.82638359, 0.82767761, 0.82721698]),
 'train_r2': array([0.88134819, 0.88192463, 0.88136882, 0.88318264, 0.88311261])}

__Conducting Hyoer Parameter Tuning.__

In [50]:
def build_model(params):

    preprocessor = ColumnTransformer(
    transformers=[
        ('numerical columns',MinMaxScaler(),num_cols),
        ('nominal categorical columns',OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False),nominal_cat_cols),
        ('ordinal categorical columns', OrdinalEncoder(categories=[traffic_order,distance_type_order]),ordinal_cat_cols)
    ],remainder='passthrough',n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False
    )

    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", XGBRegressor(**params))
    ])

    model_pipe = TransformedTargetRegressor(
        regressor=pipeline,
        transformer=PowerTransformer()
    )

    return model_pipe

In [51]:
def objective(trial):

    with mlflow.start_run(run_name=f"trial_{trial.number}",nested=True) as run:

        params = {
            "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
            "max_depth": trial.suggest_int("max_depth", 3, 12),
            "learning_rate": trial.suggest_float("learning_rate", 1e-4, 0.3, log=True),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.5, 1.0),
            "colsample_bynode": trial.suggest_float("colsample_bynode", 0.5, 1.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),   # L1
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True), # L2
            "max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            "grow_policy": trial.suggest_categorical("grow_policy", ["depthwise", "lossguide"]),
            "tree_method": "hist",  # fast histogram-based tree building
            "random_state": 42,
            "n_jobs": -1
}

        model = build_model(params)

        scores = cross_validate(
            model,
            X_train,
            y_train,
            cv = 5,
            scoring = {
                'mae': 'neg_mean_absolute_error',
                'r2': 'r2'
            },
            n_jobs = -1,
            return_train_score = True
        )

        train_mae = -scores["train_mae"].mean()
        val_mae = -scores["test_mae"].mean()
        val_mae_std = scores["test_mae"].std()
        train_r2 = scores["train_r2"].mean()
        val_r2 = scores["test_r2"].mean()

        mlflow.log_param("model_type","XGBRegressor")
        mlflow.log_param("trial_number", trial.number)
        mlflow.log_params(trial.params)

        mlflow.log_metric("train_mae_mean", train_mae)
        mlflow.log_metric("val_mae_mean", val_mae)
        mlflow.log_metric("val_mae_std", val_mae_std)
        mlflow.log_metric("train_r2_mean", train_r2)
        mlflow.log_metric("val_r2_mean", val_r2)

        for i, score in enumerate(scores["test_mae"]):
            mlflow.log_metric(f"fold_{i}_val_mae", -score)

        for i, score in enumerate(scores["test_r2"]):
            mlflow.log_metric(f"fold_{i}_val_r2", score)

        trial.set_user_attr("val_mae", val_mae)
        trial.set_user_attr("val_r2", val_r2)

        return val_mae

In [56]:
mlflow.set_experiment("Exp 4 - XGB HP Tuning")

study = optuna.create_study(direction="minimize", study_name="XGB HP Tuning")

artifact_dir = Path.cwd()
trials_path = artifact_dir / "xgb_hp_optuna_trials.csv"
params_path = artifact_dir / "xgb_best_params.json"
config_path = artifact_dir / "xgb_preprocessing_config.json"

fixed_params = {
    "tree_method": "hist",
    "random_state": 42,
    "n_jobs": -1,
}

with mlflow.start_run(run_name="XGB HP Tuning") as parent_run:
    mlflow.set_tags({
        "n_trials": 35,
        "cv_folds": 5,
        "objective_metric": "val_mae",
        "model_type": "XGBRegressor",
        "created_by": "Avanindra Bose"
    })

    study.optimize(objective, n_trials=35)

    best_trial = study.best_trial
    best_params = {**best_trial.params, **fixed_params}

    best_model_pipe = build_model(best_params)
    best_model_pipe.fit(X_train, y_train)

    y_pred_train = best_model_pipe.predict(X_train)
    y_pred_test = best_model_pipe.predict(X_test)

    train_mae = mean_absolute_error(y_train, y_pred_train)
    test_mae = mean_absolute_error(y_test, y_pred_test)
    train_r2 = r2_score(y_train, y_pred_train)
    test_r2 = r2_score(y_test, y_pred_test)

    mlflow.set_tag("best_trial_number", best_trial.number)
    mlflow.log_params({f"xgb__{k}": v for k, v in best_params.items()})

    mlflow.log_metrics({
        "best_cv_mae": best_trial.value,
        "final_train_mae": train_mae,
        "final_test_mae": test_mae,
        "final_train_r2": train_r2,
        "final_test_r2": test_r2,
    })

    trials_df = study.trials_dataframe()
    trials_df.to_csv(trials_path, index=False)

    preprocessing_config = {
        "missing_value_strategy": "dropna",
        "numerical_features": num_cols,
        "nominal_categorical_features": nominal_cat_cols,
        "ordinal_categorical_features": ordinal_cat_cols,
        "ordinal_categories": {
            "traffic": traffic_order,
            "distance_type": distance_type_order,
        },
        "numerical_scaler": "MinMaxScaler",
        "nominal_encoder": "OneHotEncoder(drop='first', handle_unknown='ignore')",
        "ordinal_encoder": "OrdinalEncoder",
        "target_transformer": "PowerTransformer",
    }

    with open(config_path, "w") as f:
        json.dump(preprocessing_config, f, indent=2)

    with open(params_path, "w") as f:
        json.dump(best_params, f, indent=2)

    mlflow.log_artifact(str(trials_path))
    mlflow.log_artifact(str(config_path))
    mlflow.log_artifact(str(params_path))

    mlflow.sklearn.log_model(
    sk_model=best_model_pipe,
    name="xgb_hp_tuned_model",
    input_example=X_train.iloc[:5],          
    signature=mlflow.models.infer_signature( 
        X_train, 
        best_model_pipe.predict(X_train)
        )
    )

[I 2026-06-04 19:01:18,617] A new study created in memory with name: XGB HP Tuning

🏃 View run trial_0 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/fb617c10a10946689aadc527a604883a
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:01:35,460] Trial 0 finished with value: 6.62979097366333 and parameters: {'n_estimators': 225, 'max_depth': 8, 'learning_rate': 0.0010355013196794885, 'min_child_weight': 1, 'gamma': 4.176521826183241, 'subsample': 0.9300149384186771, 'colsample_bytree': 0.8513361437449145, 'colsample_bylevel': 0.8125469573987565, 'colsample_bynode': 0.5537404205883265, 'reg_alpha': 2.635090920994216e-08, 'reg_lambda': 2.7261571021144227e-08, 'max_delta_step': 1, 'grow_policy': 'lossguide'}. Best is trial 0 with value: 6.62979097366333.

🏃 View run trial_1 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/7ee1e26bf5ed4b908c5f243a75461e28
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:02:19,467] Trial 1 finished with value: 3.1665180683135987 and parameters: {'n_estimators': 296, 'max_depth': 9, 'learning_rate': 0.25947613889762006, 'min_child_weight': 2, 'gamma': 1.6085463408586331, 'subsample': 0.8126869496677798, 'colsample_bytree': 0.9592070087603219, 'colsample_bylevel': 0.604933280130034, 'colsample_bynode': 0.8413090057527759, 'reg_alpha': 0.07312908259636056, 'reg_lambda': 1.6603117740506608e-06, 'max_delta_step': 8, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_2 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/c701d65d12304f128a3d436c2c5dc58c
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:02:56,753] Trial 2 finished with value: 3.431512784957886 and parameters: {'n_estimators': 930, 'max_depth': 6, 'learning_rate': 0.004257890400023857, 'min_child_weight': 9, 'gamma': 4.8947063696132105, 'subsample': 0.8954852717049453, 'colsample_bytree': 0.8081952443818393, 'colsample_bylevel': 0.7996976783172531, 'colsample_bynode': 0.8519412732074338, 'reg_alpha': 2.2655995726063743e-07, 'reg_lambda': 3.3607207926656035e-06, 'max_delta_step': 0, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_3 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/e882d5a2e93b4e8eb3221cc22221cbe7
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:03:32,822] Trial 3 finished with value: 3.1876838207244873 and parameters: {'n_estimators': 280, 'max_depth': 9, 'learning_rate': 0.10466999959980475, 'min_child_weight': 3, 'gamma': 2.6803537642138826, 'subsample': 0.5787148599958061, 'colsample_bytree': 0.8545787045634679, 'colsample_bylevel': 0.7863795054214053, 'colsample_bynode': 0.983619970833305, 'reg_alpha': 0.4506763662898604, 'reg_lambda': 2.9433369054450074e-07, 'max_delta_step': 7, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_4 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/152724d1f96f4a05b67da4d893ed0736
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:04:08,187] Trial 4 finished with value: 7.074928092956543 and parameters: {'n_estimators': 716, 'max_depth': 8, 'learning_rate': 0.00019313047946755115, 'min_child_weight': 7, 'gamma': 0.7194257756476014, 'subsample': 0.9189595318069912, 'colsample_bytree': 0.6469998802626473, 'colsample_bylevel': 0.8733089936181075, 'colsample_bynode': 0.5123886682862002, 'reg_alpha': 5.828717344646481, 'reg_lambda': 1.1442268885437126e-07, 'max_delta_step': 1, 'grow_policy': 'depthwise'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_5 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/b636ff25fbc14eebb92a32ca50809e19
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:04:44,905] Trial 5 finished with value: 5.268638324737549 and parameters: {'n_estimators': 985, 'max_depth': 10, 'learning_rate': 0.0005523349245543645, 'min_child_weight': 7, 'gamma': 2.8502089239545416, 'subsample': 0.9513246482905005, 'colsample_bytree': 0.9041708779840747, 'colsample_bylevel': 0.965962569028296, 'colsample_bynode': 0.9051885234045913, 'reg_alpha': 5.624769227340503e-06, 'reg_lambda': 0.0001826930920051132, 'max_delta_step': 5, 'grow_policy': 'depthwise'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_6 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/05cf0f00840749d595f1bec52378beb1
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:05:31,574] Trial 6 finished with value: 3.707706165313721 and parameters: {'n_estimators': 304, 'max_depth': 3, 'learning_rate': 0.08950306320364818, 'min_child_weight': 5, 'gamma': 4.787205689975412, 'subsample': 0.9154719255552886, 'colsample_bytree': 0.7757867825800245, 'colsample_bylevel': 0.9474792134607883, 'colsample_bynode': 0.6888221192083599, 'reg_alpha': 0.00206597493942434, 'reg_lambda': 9.105521626094875e-05, 'max_delta_step': 9, 'grow_policy': 'depthwise'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_7 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/acb8c933b3bb44b18453c5f217e88367
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:06:12,924] Trial 7 finished with value: 6.279402828216552 and parameters: {'n_estimators': 447, 'max_depth': 6, 'learning_rate': 0.0006797536175125128, 'min_child_weight': 4, 'gamma': 4.035314916702818, 'subsample': 0.729488239152202, 'colsample_bytree': 0.9856005056000181, 'colsample_bylevel': 0.918643671108504, 'colsample_bynode': 0.8647694986420095, 'reg_alpha': 4.738709143999615e-06, 'reg_lambda': 0.00923773036714567, 'max_delta_step': 10, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_8 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/4697c89e35654c8287756b5c2a51442d
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:06:46,243] Trial 8 finished with value: 6.705714225769043 and parameters: {'n_estimators': 651, 'max_depth': 11, 'learning_rate': 0.00031257182451429797, 'min_child_weight': 3, 'gamma': 1.3723628726339236, 'subsample': 0.9499492506264708, 'colsample_bytree': 0.6785460575834568, 'colsample_bylevel': 0.7407856285515229, 'colsample_bynode': 0.9284605070536028, 'reg_alpha': 3.7453310711986234e-08, 'reg_lambda': 1.488363846067508e-07, 'max_delta_step': 0, 'grow_policy': 'depthwise'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_9 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/ca087a0803cf4395af05080c86096adc
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:07:28,969] Trial 9 finished with value: 7.048443412780761 and parameters: {'n_estimators': 535, 'max_depth': 12, 'learning_rate': 0.00019157802429761823, 'min_child_weight': 2, 'gamma': 2.8061174515402905, 'subsample': 0.8145620202952427, 'colsample_bytree': 0.9054722104628576, 'colsample_bylevel': 0.6802356003925543, 'colsample_bynode': 0.5610067113710526, 'reg_alpha': 0.021314957568242213, 'reg_lambda': 2.1988848862648099e-07, 'max_delta_step': 5, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_10 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/88138c90b40c414fb3f7c69c28313160
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:08:04,965] Trial 10 finished with value: 4.920461273193359 and parameters: {'n_estimators': 137, 'max_depth': 3, 'learning_rate': 0.01555921232822592, 'min_child_weight': 10, 'gamma': 0.3093154119759749, 'subsample': 0.5118930166473562, 'colsample_bytree': 0.5290547773746105, 'colsample_bylevel': 0.5123624965472381, 'colsample_bynode': 0.7422778799791094, 'reg_alpha': 0.00029599265881700884, 'reg_lambda': 4.246423732587946, 'max_delta_step': 3, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_11 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/48881c3cf9214c1884f35527d982107b
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:09:07,644] Trial 11 finished with value: 3.1893829822540285 and parameters: {'n_estimators': 345, 'max_depth': 9, 'learning_rate': 0.2935612240583799, 'min_child_weight': 1, 'gamma': 1.8625746727433434, 'subsample': 0.611901399310562, 'colsample_bytree': 0.9947548824948425, 'colsample_bylevel': 0.587626190093594, 'colsample_bynode': 0.7670548699625337, 'reg_alpha': 1.054724684900098, 'reg_lambda': 1.0693143967572004e-05, 'max_delta_step': 8, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_12 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/84198860f2b74ddcb4816eab6c60af84
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:10:05,683] Trial 12 finished with value: 3.238416385650635 and parameters: {'n_estimators': 107, 'max_depth': 7, 'learning_rate': 0.055231736484061884, 'min_child_weight': 5, 'gamma': 2.4228817165898184, 'subsample': 0.7031310096596797, 'colsample_bytree': 0.9176778383331645, 'colsample_bylevel': 0.6471978572635815, 'colsample_bynode': 0.9830640627147937, 'reg_alpha': 0.09536658742228181, 'reg_lambda': 4.059986807749867e-06, 'max_delta_step': 7, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_13 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/485089c793a74e7085f0e9bd28806aa1
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:11:29,038] Trial 13 finished with value: 3.245869541168213 and parameters: {'n_estimators': 411, 'max_depth': 10, 'learning_rate': 0.2897413600970671, 'min_child_weight': 3, 'gamma': 1.4335813576496552, 'subsample': 0.5542288684644145, 'colsample_bytree': 0.7719535780919002, 'colsample_bylevel': 0.5046050366429761, 'colsample_bynode': 0.9952223889754925, 'reg_alpha': 0.18253681581960177, 'reg_lambda': 0.0012511984656267327, 'max_delta_step': 6, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_14 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/2b8438f5ba6c49a0a677becc3f5b884d
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:12:45,067] Trial 14 finished with value: 3.5057249546051024 and parameters: {'n_estimators': 262, 'max_depth': 5, 'learning_rate': 0.06694820645532534, 'min_child_weight': 3, 'gamma': 3.401789092378215, 'subsample': 0.6415176843276145, 'colsample_bytree': 0.7077077288842278, 'colsample_bylevel': 0.715782585413102, 'colsample_bynode': 0.8086114861854513, 'reg_alpha': 0.003375002864463107, 'reg_lambda': 0.04156658272564114, 'max_delta_step': 8, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_15 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/0a2c5939de304145820d9a775bf1890c
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:14:01,092] Trial 15 finished with value: 3.236779069900513 and parameters: {'n_estimators': 517, 'max_depth': 9, 'learning_rate': 0.020993745420618434, 'min_child_weight': 5, 'gamma': 1.970761956537691, 'subsample': 0.8109193761891297, 'colsample_bytree': 0.8533394232584309, 'colsample_bylevel': 0.5900078234861401, 'colsample_bynode': 0.6519034053407513, 'reg_alpha': 4.7581385374509075, 'reg_lambda': 1.142539230547677e-06, 'max_delta_step': 10, 'grow_policy': 'lossguide'}. Best is trial 1 with value: 3.1665180683135987.

🏃 View run trial_16 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/3fa9db4a84fa4fa390dc93118389335a
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:15:22,106] Trial 16 finished with value: 3.0463255405426026 and parameters: {'n_estimators': 229, 'max_depth': 12, 'learning_rate': 0.14550339872440116, 'min_child_weight': 2, 'gamma': 0.9401686870430421, 'subsample': 0.8192583453839631, 'colsample_bytree': 0.9480655737279361, 'colsample_bylevel': 0.8121181265740157, 'colsample_bynode': 0.9153354065584236, 'reg_alpha': 0.00026369615574780073, 'reg_lambda': 1.4161140314789387e-08, 'max_delta_step': 4, 'grow_policy': 'lossguide'}. Best is trial 16 with value: 3.0463255405426026.

🏃 View run trial_17 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/727c306dbc3740de9f4ca0bf19c41b9e
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:16:42,502] Trial 17 finished with value: 3.0653472900390626 and parameters: {'n_estimators': 197, 'max_depth': 12, 'learning_rate': 0.019858878414331104, 'min_child_weight': 1, 'gamma': 0.014696170774372574, 'subsample': 0.7929302924037481, 'colsample_bytree': 0.9578500348684654, 'colsample_bylevel': 0.8599600739768459, 'colsample_bynode': 0.825756698705425, 'reg_alpha': 7.088929174691109e-05, 'reg_lambda': 1.2999908314086947e-08, 'max_delta_step': 4, 'grow_policy': 'lossguide'}. Best is trial 16 with value: 3.0463255405426026.

🏃 View run trial_18 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/dc23cbb6c5fe43df8c2b5c9df4320dbc
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:18:05,191] Trial 18 finished with value: 3.6986945152282713 and parameters: {'n_estimators': 172, 'max_depth': 12, 'learning_rate': 0.007191903528215102, 'min_child_weight': 1, 'gamma': 0.01569082151814638, 'subsample': 0.7367627107548769, 'colsample_bytree': 0.9424844260355099, 'colsample_bylevel': 0.8636992382672316, 'colsample_bynode': 0.9264750506110087, 'reg_alpha': 4.189239173727494e-05, 'reg_lambda': 1.4299555037679977e-08, 'max_delta_step': 3, 'grow_policy': 'depthwise'}. Best is trial 16 with value: 3.0463255405426026.

🏃 View run trial_19 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/0ad2fa3d21d04ed9a5e5093e548e4058
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:19:33,838] Trial 19 finished with value: 3.025645208358765 and parameters: {'n_estimators': 381, 'max_depth': 11, 'learning_rate': 0.022009166409812087, 'min_child_weight': 2, 'gamma': 0.7556266326433903, 'subsample': 0.861084113301299, 'colsample_bytree': 0.9987523864184132, 'colsample_bylevel': 0.999034664993629, 'colsample_bynode': 0.7671890970572979, 'reg_alpha': 8.309092225896197e-05, 'reg_lambda': 1.1339655711348272e-08, 'max_delta_step': 3, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_20 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/a3ec8136cd474786a49ad5c995b42d42
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:20:53,345] Trial 20 finished with value: 3.030645418167114 and parameters: {'n_estimators': 407, 'max_depth': 11, 'learning_rate': 0.0368046619530861, 'min_child_weight': 4, 'gamma': 0.8944300837873076, 'subsample': 0.9950042567104965, 'colsample_bytree': 0.9970962110153182, 'colsample_bylevel': 0.9862670896573407, 'colsample_bynode': 0.6798466159411554, 'reg_alpha': 1.1964634127251825e-06, 'reg_lambda': 4.384858603455965e-05, 'max_delta_step': 3, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_21 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/c0bbb38e44f44f61ab2e6f9850db419d
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:22:07,181] Trial 21 finished with value: 3.0356618881225588 and parameters: {'n_estimators': 407, 'max_depth': 11, 'learning_rate': 0.03364860439234696, 'min_child_weight': 4, 'gamma': 1.08665709530894, 'subsample': 0.9909512325418777, 'colsample_bytree': 0.9947235088131382, 'colsample_bylevel': 0.977415532388135, 'colsample_bynode': 0.6728215646579652, 'reg_alpha': 1.3457106542528393e-06, 'reg_lambda': 2.9897772173277486e-05, 'max_delta_step': 3, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_22 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/c53ba42dae094352a65d7dd4ac4beece
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:23:50,752] Trial 22 finished with value: 3.0294884204864503 and parameters: {'n_estimators': 417, 'max_depth': 11, 'learning_rate': 0.03323773621472208, 'min_child_weight': 6, 'gamma': 0.8664965772158052, 'subsample': 0.979452853681607, 'colsample_bytree': 0.9999914120343948, 'colsample_bylevel': 0.9894717795653191, 'colsample_bynode': 0.6561688172833441, 'reg_alpha': 9.246997473850131e-07, 'reg_lambda': 4.646020556964347e-05, 'max_delta_step': 2, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_23 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/a4c1e01d7ffa447d993b4ad1796bb34b
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:25:45,356] Trial 23 finished with value: 3.0525522232055664 and parameters: {'n_estimators': 579, 'max_depth': 11, 'learning_rate': 0.005900002074307026, 'min_child_weight': 7, 'gamma': 0.7260315535505691, 'subsample': 0.9960582016034042, 'colsample_bytree': 0.9988727078186386, 'colsample_bylevel': 0.9988595527395295, 'colsample_bynode': 0.625487016347725, 'reg_alpha': 5.477484142065727e-07, 'reg_lambda': 0.000684818699478547, 'max_delta_step': 2, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_24 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/a81cecc2174142169c7298863ef3ca49
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:26:38,114] Trial 24 finished with value: 3.039135456085205 and parameters: {'n_estimators': 490, 'max_depth': 10, 'learning_rate': 0.010299579311837326, 'min_child_weight': 6, 'gamma': 0.49472127351430584, 'subsample': 0.8732338507016585, 'colsample_bytree': 0.8939322080206402, 'colsample_bylevel': 0.914207314039762, 'colsample_bynode': 0.736602566191476, 'reg_alpha': 1.769218052747517e-05, 'reg_lambda': 0.2546429964482403, 'max_delta_step': 2, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_25 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/758f445781e04234b8a1e20860e1ac7d
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:27:57,433] Trial 25 finished with value: 4.06839075088501 and parameters: {'n_estimators': 368, 'max_depth': 11, 'learning_rate': 0.002818404967297704, 'min_child_weight': 6, 'gamma': 1.11525131554535, 'subsample': 0.8684223629043125, 'colsample_bytree': 0.9379806478443301, 'colsample_bylevel': 0.9282502314041792, 'colsample_bynode': 0.6065794481346639, 'reg_alpha': 2.3637572051876024e-07, 'reg_lambda': 0.0024660440632884827, 'max_delta_step': 2, 'grow_policy': 'lossguide'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_26 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/260fe581a95b4269ae44d2544f89c57a
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:29:21,449] Trial 26 finished with value: 3.572635221481323 and parameters: {'n_estimators': 746, 'max_depth': 10, 'learning_rate': 0.002107197337878015, 'min_child_weight': 8, 'gamma': 2.043602382862141, 'subsample': 0.9788578644530607, 'colsample_bytree': 0.8756600277506259, 'colsample_bylevel': 0.9887300723576244, 'colsample_bynode': 0.7159034922075409, 'reg_alpha': 1.9810872767576083e-06, 'reg_lambda': 4.342256509536421e-05, 'max_delta_step': 4, 'grow_policy': 'depthwise'}. Best is trial 19 with value: 3.025645208358765.

🏃 View run trial_27 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/631b86e76f21469688b5c92254511449
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:29:57,506] Trial 27 finished with value: 3.022345781326294 and parameters: {'n_estimators': 603, 'max_depth': 11, 'learning_rate': 0.03417913351080966, 'min_child_weight': 4, 'gamma': 0.452621135308464, 'subsample': 0.863443370509037, 'colsample_bytree': 0.9651511117267577, 'colsample_bylevel': 0.8881626404741021, 'colsample_bynode': 0.7870334195129309, 'reg_alpha': 8.213030683468667e-08, 'reg_lambda': 0.2436995143218315, 'max_delta_step': 1, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.

🏃 View run trial_28 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/a73e3d449b574cc5a089d60ecc88291e
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:31:06,193] Trial 28 finished with value: 3.0305041790008547 and parameters: {'n_estimators': 613, 'max_depth': 10, 'learning_rate': 0.03740741167143384, 'min_child_weight': 6, 'gamma': 0.4479090006412027, 'subsample': 0.851818945634926, 'colsample_bytree': 0.9583218022441267, 'colsample_bylevel': 0.8897664216569203, 'colsample_bynode': 0.7878672902172649, 'reg_alpha': 1.5687497519079035e-08, 'reg_lambda': 8.936445032076309, 'max_delta_step': 1, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.

🏃 View run trial_29 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/cf1751683e87444382a1c1363a9b2e23
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:32:22,548] Trial 29 finished with value: 3.0859273433685304 and parameters: {'n_estimators': 825, 'max_depth': 8, 'learning_rate': 0.011829953083208227, 'min_child_weight': 4, 'gamma': 0.3377856949235341, 'subsample': 0.7743779670653719, 'colsample_bytree': 0.8228582127308538, 'colsample_bylevel': 0.9447529809381714, 'colsample_bynode': 0.5792000846564197, 'reg_alpha': 8.816441487407417e-08, 'reg_lambda': 0.047722718414174754, 'max_delta_step': 1, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.

🏃 View run trial_30 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/4af2a2a2c96141eab61b4c01adb31a47
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:33:26,531] Trial 30 finished with value: 3.061377000808716 and parameters: {'n_estimators': 643, 'max_depth': 12, 'learning_rate': 0.027764296142659295, 'min_child_weight': 5, 'gamma': 1.2740724547527567, 'subsample': 0.8551773355076642, 'colsample_bytree': 0.8793107183117779, 'colsample_bylevel': 0.8378206024285059, 'colsample_bynode': 0.7679932583687809, 'reg_alpha': 1.0152175309060396e-08, 'reg_lambda': 0.8004843912240102, 'max_delta_step': 0, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.

🏃 View run trial_31 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/06c560f6b7c24223968be9e70da66c69
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:34:34,673] Trial 31 finished with value: 3.036152982711792 and parameters: {'n_estimators': 596, 'max_depth': 10, 'learning_rate': 0.05152657113983173, 'min_child_weight': 6, 'gamma': 0.5385308875640883, 'subsample': 0.8469795854084249, 'colsample_bytree': 0.9580426736481537, 'colsample_bylevel': 0.8947501423942553, 'colsample_bynode': 0.7871448216285121, 'reg_alpha': 1.0328744596878684e-08, 'reg_lambda': 9.351872682641504, 'max_delta_step': 1, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.

🏃 View run trial_32 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/6c499625eedb451dafec9d3189dc9071
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:36:02,690] Trial 32 finished with value: 3.072168779373169 and parameters: {'n_estimators': 727, 'max_depth': 11, 'learning_rate': 0.15880693168857082, 'min_child_weight': 8, 'gamma': 0.15495014388471684, 'subsample': 0.8885442458057567, 'colsample_bytree': 0.9239705699448808, 'colsample_bylevel': 0.9018605259831038, 'colsample_bynode': 0.7135060001352795, 'reg_alpha': 4.511067907800508e-08, 'reg_lambda': 1.024493016700219, 'max_delta_step': 2, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.

🏃 View run trial_33 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/d6247c34145c47a9b1b693ce25d6c332
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:37:18,728] Trial 33 finished with value: 3.0465901851654054 and parameters: {'n_estimators': 587, 'max_depth': 9, 'learning_rate': 0.039634567177513826, 'min_child_weight': 6, 'gamma': 0.6058356338406817, 'subsample': 0.7591331610065966, 'colsample_bytree': 0.9644039422985538, 'colsample_bylevel': 0.9477142587934383, 'colsample_bynode': 0.7966500966291707, 'reg_alpha': 1.679189010062973e-07, 'reg_lambda': 1.8860641630342156, 'max_delta_step': 1, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.

🏃 View run trial_34 at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/85615548d94e4b9fa707556f78a757f5
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

[I 2026-06-04 19:38:07,407] Trial 34 finished with value: 3.072011041641235 and parameters: {'n_estimators': 486, 'max_depth': 10, 'learning_rate': 0.012908085776128111, 'min_child_weight': 2, 'gamma': 1.6599883563273727, 'subsample': 0.8453863773170331, 'colsample_bytree': 0.968172043596212, 'colsample_bylevel': 0.7740179941235721, 'colsample_bynode': 0.869586357578519, 'reg_alpha': 4.2296754138381234e-07, 'reg_lambda': 0.11647228671659704, 'max_delta_step': 0, 'grow_policy': 'lossguide'}. Best is trial 27 with value: 3.022345781326294.
c:\Users\avanindra Bose\Urban Eats Delivery Time Prediction\UrbanEats-Delivery-Time-Prediction\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:978: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\avanindra Bose\Urban Eats Delivery Time Prediction\UrbanEats-Delivery-Time-Prediction\.venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/06/04 19:39:05 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/06/04 19:39:22 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 241.73it/s]

🏃 View run XGB HP Tuning at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5/runs/b49702f40cbd4581a53f8b131c566df7
🧪 View experiment at: https://dagshub.com/AvanindraBose/Urban-Eats-Food-Delivery-Time-Prediction.mlflow/#/experiments/5

In [59]:
best_trial.params

{'n_estimators': 603,
 'max_depth': 11,
 'learning_rate': 0.03417913351080966,
 'min_child_weight': 4,
 'gamma': 0.452621135308464,
 'subsample': 0.863443370509037,
 'colsample_bytree': 0.9651511117267577,
 'colsample_bylevel': 0.8881626404741021,
 'colsample_bynode': 0.7870334195129309,
 'reg_alpha': 8.213030683468667e-08,
 'reg_lambda': 0.2436995143218315,
 'max_delta_step': 1,
 'grow_policy': 'lossguide'}

In [57]:
best_params

{'n_estimators': 603,
 'max_depth': 11,
 'learning_rate': 0.03417913351080966,
 'min_child_weight': 4,
 'gamma': 0.452621135308464,
 'subsample': 0.863443370509037,
 'colsample_bytree': 0.9651511117267577,
 'colsample_bylevel': 0.8881626404741021,
 'colsample_bynode': 0.7870334195129309,
 'reg_alpha': 8.213030683468667e-08,
 'reg_lambda': 0.2436995143218315,
 'max_delta_step': 1,
 'grow_policy': 'lossguide',
 'tree_method': 'hist',
 'random_state': 42,
 'n_jobs': -1}

In [60]:
best_trial.value

3.022345781326294

In [61]:
optuna.visualization.plot_optimization_history(study)

In [62]:
optuna.visualization.plot_param_importances(study)

In [63]:
optuna.visualization.plot_slice(study)